version: "3.7"

services:
  image-to-hash:
    build:
      context: .
      dockerfile: Dockerfile
    image: image-to-hash:latest
    container_name: image-to-hash
    restart: always
    command: "yarn dev"
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - mysql-database

  mysql-database:
    image: mysql:latest
    container_name: mysql-database
    restart: always
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
